### ISSUE TITLE
Server crashes when drawer leaves in games with more than 3 players

### ISSUE THREAD

**Issue by WilsonCWong** [JunYuHuang/INFO4290-Project#3]
Reproduction steps:
1. Create lobby with three players
2. Start the game
3. Have the drawer leave
4. Make the other two players guess the word
5. Server crashes

**Comment by JunYuHuang** [comment]
Resolved issue by:
- Implementing a check for prematurely ending a turn if the drawer leaves while the turn was in progress.
- Only rewarding the drawer points at the end of the turn if the drawer was still in the room then.
